#!/bin/bash
python run_tozs.py toz 1
python run_tozs.py toz 2 > mah_toz
python run_tozs.py toz 3 >> mah_toz
python run_tozs.py toz 4 >> mah_toz
python run_tozs.py toz 5 >> mah_toz
python run_tozs.py toz 6 >> mah_toz
python run_tozs.py toz 7 >> mah_toz
python run_tozs.py toz 8 >> mah_toz
python run_tozs.py toz 9 >> mah_toz
python run_tozs.py toz 10 >> mah_toz

python run_tozs.py csp 1
python run_tozs.py csp 2 > mah_csp
python run_tozs.py csp 3 >> mah_csp
python run_tozs.py csp 4 >> mah_csp
python run_tozs.py csp 5 >> mah_csp
python run_tozs.py csp 6 >> mah_csp
python run_tozs.py csp 7 >> mah_csp
python run_tozs.py csp 8 >> mah_csp
python run_tozs.py csp 9 >> mah_csp
python run_tozs.py csp 10 >> mah_csp

python run_tozs.py hjorth 1
python run_tozs.py hjorth 2 > mah_hjorth
python run_tozs.py hjorth 3 >> mah_hjorth
python run_tozs.py hjorth 4 >> mah_hjorth
python run_tozs.py hjorth 5 >> mah_hjorth
python run_tozs.py hjorth 6 >> mah_hjorth
python run_tozs.py hjorth 7 >> mah_hjorth
python run_tozs.py hjorth 8 >> mah_hjorth
python run_tozs.py hjorth 9 >> mah_hjorth
python run_tozs.py hjorth 10 >> mah_hjorth

python mahala_draw.py